apiVersion: v1
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      image:
        imageType: distroless
      proxyMetadata:
        ISTIO_META_ENABLE_HBONE: "true"
    defaultProviders:
      metrics:
      - prometheus
    enablePrometheusMerge: true
    rootNamespace: istio-system
    serviceScopeConfigs:
    - scope: GLOBAL
      servicesSelector:
        matchExpressions:
        - key: istio.io/global
          operator: In
          values:
          - "true"
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
kind: ConfigMap
metadata:
  creationTimestamp: "2026-07-15T19:17:26Z"
  labels:
    app.kubernetes.io/instance: istio
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istiod
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 1.30.2
    helm.sh/chart: istiod-1.30.2
    install.operator.istio.io/owning-resource: unknown
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio.io/rev: default
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.30.2
    release: istio
  name: istio
  namespace: istio-system
  resourceVersion: "34436"
  uid: 3bf61956-1905-44be-b74f-5f82cd94f47a
