apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
  namespace: istio-system
  labels:
    app.kubernetes.io/instance: istio
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istiod
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 1.30.2
    helm.sh/chart: istiod-1.30.2
    install.operator.istio.io/owning-resource: unknown
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio.io/rev: default
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.30.2
    release: istio
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      image:
        imageType: distroless
      proxyMetadata:
        ISTIO_META_ENABLE_HBONE: "true"
    defaultProviders:
      metrics:
      - prometheus
    enablePrometheusMerge: true
    extensionProviders:
    - name: jaeger-zipkin
      zipkin:
        service: zipkin.istio-system.svc.cluster.local
        port: 9411
    rootNamespace: istio-system
    serviceScopeConfigs:
    - scope: GLOBAL
      servicesSelector:
        matchExpressions:
        - key: istio.io/global
          operator: In
          values:
          - "true"
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
